language: android
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.0
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
script:
  - ./gradlew assembleDebug
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
notifications:
  email: false